export enum AgeGroup {
  AGE_15_19 = '15-19',
  AGE_20_24 = '20-24',
  AGE_25_29 = '25-29',
  AGE_30_34 = '30-34',
  AGE_35_39 = '35-39',
  AGE_40_PLUS = '40+',
}

/** Map first 1-2 digits of Brazilian CEP to region/state */
export const CEP_REGION_MAP: Record<string, { region: string; state: string }> = {
  '01': { region: 'Sudeste', state: 'SP' }, '02': { region: 'Sudeste', state: 'SP' },
  '03': { region: 'Sudeste', state: 'SP' }, '04': { region: 'Sudeste', state: 'SP' },
  '05': { region: 'Sudeste', state: 'SP' }, '06': { region: 'Sudeste', state: 'SP' },
  '07': { region: 'Sudeste', state: 'SP' }, '08': { region: 'Sudeste', state: 'SP' },
  '09': { region: 'Sudeste', state: 'SP' },
  '1': { region: 'Sudeste', state: 'SP' },
  '20': { region: 'Sudeste', state: 'RJ' }, '21': { region: 'Sudeste', state: 'RJ' },
  '22': { region: 'Sudeste', state: 'RJ' }, '23': { region: 'Sudeste', state: 'RJ' },
  '24': { region: 'Sudeste', state: 'RJ' }, '25': { region: 'Sudeste', state: 'RJ' },
  '26': { region: 'Sudeste', state: 'RJ' }, '27': { region: 'Sudeste', state: 'RJ' },
  '28': { region: 'Sudeste', state: 'RJ' },
  '29': { region: 'Sudeste', state: 'ES' },
  '30': { region: 'Sudeste', state: 'MG' }, '31': { region: 'Sudeste', state: 'MG' },
  '32': { region: 'Sudeste', state: 'MG' }, '33': { region: 'Sudeste', state: 'MG' },
  '34': { region: 'Sudeste', state: 'MG' }, '35': { region: 'Sudeste', state: 'MG' },
  '36': { region: 'Sudeste', state: 'MG' }, '37': { region: 'Sudeste', state: 'MG' },
  '38': { region: 'Sudeste', state: 'MG' }, '39': { region: 'Sudeste', state: 'MG' },
  '40': { region: 'Nordeste', state: 'BA' }, '41': { region: 'Nordeste', state: 'BA' },
  '42': { region: 'Nordeste', state: 'BA' }, '43': { region: 'Nordeste', state: 'BA' },
  '44': { region: 'Nordeste', state: 'BA' }, '45': { region: 'Nordeste', state: 'BA' },
  '46': { region: 'Nordeste', state: 'BA' }, '47': { region: 'Nordeste', state: 'BA' },
  '48': { region: 'Nordeste', state: 'BA' },
  '49': { region: 'Nordeste', state: 'SE' },
  '50': { region: 'Nordeste', state: 'PE' }, '51': { region: 'Nordeste', state: 'PE' },
  '52': { region: 'Nordeste', state: 'PE' }, '53': { region: 'Nordeste', state: 'PE' },
  '54': { region: 'Nordeste', state: 'PE' }, '55': { region: 'Nordeste', state: 'PE' },
  '56': { region: 'Nordeste', state: 'PE' },
  '57': { region: 'Nordeste', state: 'AL' },
  '58': { region: 'Nordeste', state: 'PB' },
  '59': { region: 'Nordeste', state: 'RN' },
  '60': { region: 'Nordeste', state: 'CE' }, '61': { region: 'Nordeste', state: 'CE' },
  '62': { region: 'Nordeste', state: 'CE' }, '63': { region: 'Nordeste', state: 'CE' },
  '64': { region: 'Nordeste', state: 'PI' },
  '65': { region: 'Nordeste', state: 'MA' },
  '66': { region: 'Norte', state: 'PA' }, '67': { region: 'Norte', state: 'PA' },
  '68': { region: 'Norte', state: 'AP' },
  '69': { region: 'Norte', state: 'AM' },
  '70': { region: 'Centro-Oeste', state: 'DF' }, '71': { region: 'Centro-Oeste', state: 'DF' },
  '72': { region: 'Centro-Oeste', state: 'GO' }, '73': { region: 'Centro-Oeste', state: 'GO' },
  '74': { region: 'Centro-Oeste', state: 'GO' }, '75': { region: 'Centro-Oeste', state: 'GO' },
  '76': { region: 'Centro-Oeste', state: 'GO' },
  '77': { region: 'Norte', state: 'TO' },
  '78': { region: 'Centro-Oeste', state: 'MT' },
  '79': { region: 'Centro-Oeste', state: 'MS' },
  '80': { region: 'Sul', state: 'PR' }, '81': { region: 'Sul', state: 'PR' },
  '82': { region: 'Sul', state: 'PR' }, '83': { region: 'Sul', state: 'PR' },
  '84': { region: 'Sul', state: 'PR' }, '85': { region: 'Sul', state: 'PR' },
  '86': { region: 'Sul', state: 'PR' }, '87': { region: 'Sul', state: 'PR' },
  '88': { region: 'Sul', state: 'SC' }, '89': { region: 'Sul', state: 'SC' },
  '90': { region: 'Sul', state: 'RS' }, '91': { region: 'Sul', state: 'RS' },
  '92': { region: 'Sul', state: 'RS' }, '93': { region: 'Sul', state: 'RS' },
  '94': { region: 'Sul', state: 'RS' }, '95': { region: 'Sul', state: 'RS' },
  '96': { region: 'Sul', state: 'RS' }, '97': { region: 'Sul', state: 'RS' },
  '98': { region: 'Sul', state: 'RS' }, '99': { region: 'Sul', state: 'RS' },
};
